module SellerMarket
  BANNER_THUMBNAIL_SIZES = { :full_width => "866x100>"}
  BANNER_SIZE_HELP_TEXT = "the optimal size is 866 x 100 px"
  FEATURED_PRODUCT_ROW_LIMIT = 3
  FEATURED_PRODUCT_LIMIT = FEATURED_PRODUCT_ROW_LIMIT * (MARKET_UNITS_PER_ROW - 1)
end